- id: doi:10.1162/imag_a_00400
  type: paper
  description: The paper describing the Hidden multivariate pattern method
  date: 2024-12-16
  image: https://mitp.silverchair-cdn.com/mitp/content_public/journal/imag/2/10.1162_imag_a_00400/4/imag_a_00400_fig1.png?Expires=1769599620&Signature=1zBPWdiIwhuKjLt1F7tx4eIZRc6tY0scEpsr9Uaca8TESdGU4hbCB7QkQOVVv4KZnj1SapXPX7xndQsqwkxSfZFVw5FmEJUdPF4ujGRIriQmDkqq9tTR1qg~NrUlmfhxprFT2TouAVRCNWrgeZ0McF7R4D0FPzVCJ-SCypIs1uZSlPihN1SXxGTViPbxE3iNnnmkJwfCy6ajG5JjtqG4TfG5vJlom8y4hnvH9ogF3V6e2VVWMr1CstV4mEgwX~9jH649~MsIfpjwPbKRTDb2pasAUSRGM~uFHQvOAEGKu8~oF61yWbfOCZbeyv9FUbtgI9RyTKrVmpIRI1ZpEILEtQ__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  buttons:
    - type: python package
      link: https://github.com/GWeindel/hmp/
    - type: website
      link: https://hmp.readthedocs.io/en/latest/welcome.html
  tags:
    - open science
  repo: GWeindel/hmp

- id: doi:10.7554/eLife.108049
  image: https://iiif.elifesciences.org/epp/108049%2Fv2%2Fcontent%2F661505v2_fig3.tif/full/max/0/default.jpg

- id: doi:10.23668/psycharchives.21167
  buttons:
    - type: preprint
      link: https://doi.org/10.23668/psycharchives.21167